name: Build and Deploy Examples

on:
  push:
    branches:
      - master
    paths:
      - 'examples/**'
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build-examples.yml'
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - 'examples/**'
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build-examples.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.25.0'

      - name: Build Trash
        run: go build -o trash .

      - name: Configure Base URL for Examples
        run: |
          sed -i '/^\[site\]/a base = "\/trash\/blog"' examples/blog/Trash.toml
          sed -i '/^\[site\]/a base = "\/trash\/personal"' examples/personal/Trash.toml
          
      - name: Build Examples
        run: |
          TRASH_NO_SANDBOX=1 ./trash build ./examples/blog
          TRASH_NO_SANDBOX=1 ./trash build ./examples/personal
          
          mkdir -p _site/blog/
          mkdir -p _site/personal/

          cp examples/index.html _site/

          cp -r examples/blog/out/* _site/blog/
          cp -r examples/personal/out/* _site/personal/

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./_site

  deploy:
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
