name: Build and Deploy Examples

on:
  push:
    branches:
      - main
    paths:
      - 'examples/**'
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build-examples.yml'
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'examples/**'
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build-examples.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.25.0'

      - name: Build Trash
        run: go build -o trash .
          
      - name: Build Examples
        run: |
          echo "Building blog example..."
          ./trash build ./examples/blog
    
          echo "Building personal example..."
          ./trash build ./examples/personal
          
          mkdir -p _site
          cp examples/index.html _site/
          cp -r examples/blog/out/* _site/blog/
          cp -r examples/personal/out/* _site/personal/

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./_site

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
